name: Release PyPI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release_pypi skip')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup dependencies
        run: pip3 install wheel

      - name: Build wheel
        run: |
          python3 setup.py bdist_wheel
          python3 setup.py sdist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}